#! /bin/bash

# User data
export EMAIL="mxu2008@hotmail.com" #qa | "martin17xu@gmail.com" # dev
export PASSWORD="Nz0619??" #qa | "Nz0619??++" # dev

# Cognito data
export USER_POOL_ID="us-west-2_e457a1pKM" # qa | "us-west-2_HI8y5rCpg" # dev
export CLIENT_ID="3kj66ctad6bh3j46nv47u62soe" # qa | "7jj1nk6b21uvn35i33achlbc56" # dev

# MFA data
export MFA_CODE="971642" # replace it with your own MFA code you received from email
# replace it with the sessnion token from step 1
export SESSION_TOKEN="AYABeNLZx2JJxDq3cXxZ-igl6ZMAHQABAAdTZXJ2aWNlABBDb2duaXRvVXNlclBvb2xzAAEAB2F3cy1rbXMAS2Fybjphd3M6a21zOnVzLXdlc3QtMjowMTU3MzY3MjcxOTg6a2V5LzI5OTFhNGE5LTM5YTAtNDQ0Mi04MWU4LWRkYjY4NTllMTg2MQC4AQIBAHiLcRcG62Mb19KUM6qQUoajwNOF_-4FakXKLIP1RcBYjQGOaGNbxi-WuwOjiU8Ej7hNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDTbU87h5O5nL2wmYAgEQgDuNGUtASDNbwJvZnvf9bbfqd7_kSsNRD3HjyjtSRkZCcn46ZDDpKV70FhtHake5t9FFP-Xn46LjzMg8cQIAAAAADAAAEAAAAAAAAAAAAAAAAABS03stjGI2eoj-S0nsD6So_____wAAAAEAAAAAAAAAAAAAAAEAAAHYyb735Cc0BseA89PK09mMLKOioBnWSA52FfSPievZdO-DM0fYZqrHnUYX7S1wTInGVSCwimrm9en36hPC0AbmPjjsgTJRArWk3Y3j5P6aNai5ATi7JH-Cqy9KEHjwz8AXktP0aXdM9M97CXDx0OMcyq6eGTCmpKGm0b9OSSvxYjnMHo2ZlT-JS7hzgcH-ZDc-4QXztlkRcofp8-X2PnvgC4c3K26SrVWF25Ephtw1oCFOMLmDjxprKknPWMVIjoyy-LO9LMLEtgZawrBO2ArlawhLcvZ9gI020O3dS_Y1fJKu02nwN7BtPJi20FgV33651UPiYQYt_Qzv-GFEnIGCRWTrAmMnr4XISAyh9E4DxfSlpPci-N0mazj1fF5ZnOjHYWDCwxnd0DyYgYQCkh8RK74H1eVJIaju6CyO4jCrCGc49fy-7NNDvNcD5jnEjBkYG7jffJNg1RlS9NtnFBiYR4G3WLpzdc3yFwjufS3M0IFkgZknMfaR3tUjFYyQ0bZpJwtDxfaQsZYJ3czSf0EtuVUrcB8_2Rz4VTpcgf6yFMJIwMhtxyc2igCHogo_h3Eu-zKNp-KtVMveixchiM4gv904xB89bV8HgfW_Z7K6C92ixkYdBMy59o1AC06Rm8HDmFZo4NghBrQ"



# Store a permanent password (newly onboarded user)
if false; then
   aws cognito-idp admin-set-user-password --profile viewlinc-sandbox --region us-west-2 --user-pool-id ${USER_POOL_ID}  --username ${EMAIL} --password ${PASSWORD} --permanent
fi

# Step1: Generate MFA code and session token
if true; then
   jwt_token=$(aws cognito-idp initiate-auth \
     --region "us-west-2" \
     --client-id ${CLIENT_ID} \
     --auth-flow USER_PASSWORD_AUTH \
     --auth-parameters USERNAME=${EMAIL},PASSWORD=${PASSWORD} \
   )
   #--query 'AuthenticationResult.IdToken')
   #--user-context-data "user=daniel.rodrigues@vaisala.com,poolid=us-west-2_T2w6gQqDB,clientid=3or8f5hk3on1ev9epjkfkkd0u9" (something like this, but generated by API)
   echo "JWT"
   echo $jwt_token
fi


# Step 2: Create JWT token 
if false; then
   mfa_response=$(aws cognito-idp respond-to-auth-challenge \
      --region "us-west-2" \
      --client-id ${CLIENT_ID} \
      --challenge-name SMS_MFA \
      --challenge-responses SMS_MFA_CODE=${MFA_CODE},USERNAME=${EMAIL} \
      --session ${SESSION_TOKEN}
   )
   echo "MFA RESPOND CHALLENG RESPONSE"
   echo $mfa_response
   echo
   echo
   echo
fi






